# Generated by Django 6.0 on 2026-08-18 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_notic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notic',
            new_name='Notice',
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'verbose_name': 'Notice', 'verbose_name_plural': 'Notices'},
        ),
    ]
